name: Build and install QtAseman
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and install QtAseman
    steps:
      -uses: jurplel/install-qt-action@v2
      version: 5.15.2
      -uses: actions/checkout@v2
      with:
        repository: Aseman-Land/QtAseman
        submodules: recursive
      -run: |
        mkdir build
        cd build
        qmake -r ..
      -run: make -j2
      -run: make install

